class Cons:

    FILE_PATH = r'G:\Coding Hub\Python\CreateFormMapping\FormMapping.xlsx'

    EXCEL_ITEM_START_CELL = 'A2'
    EXCEL_ITEM_END_CELL = 'D100'

    EXCEL_QCAT_FORM_TEMPLATE_ID_CELL = 'E2'
    EXCEL_SF_FORM_TEMPLATE_ID_CELL = 'F2'
    EXCEL_QCAT_FORM_NAME_CELL = 'G2'
    EXCEL_FIELD_COUNT_CELL = 'H2'
    EXCEL_COMMENT_CELL = 'I2'

    EXCEL_FILE_NAME_CELL = 'J2'
